SELECT
    DISTINCT A.ROLNAME AS USER_ROLE_NAME,
    C.ROLNAME AS MEMBER_OF,
    ARRAY_TO_STRING(ARRAY_AGG(DISTINCT D.PRIVILEGE_TYPE),',') AS PRIVILEGE,
    D.TABLE_SCHEMA || '.' || D.TABLE_NAME AS TABLENAME
FROM PG_ROLES A
INNER JOIN PG_AUTH_MEMBERS B ON A.OID = B.MEMBER
INNER JOIN PG_ROLES C ON B.ROLEID = C.OID
LEFT JOIN INFORMATION_SCHEMA.ROLE_TABLE_GRANTS D ON D.GRANTEE = C.ROLNAME
WHERE A.ROLNAME not in ('pg_monitor','rds_superuser','rds_superuser')
    AND D.TABLE_NAME IS NOT NULL
   --AND C.ROLNAME != 'admin'
   AND D.PRIVILEGE_TYPE != 'SELECT' 
GROUP BY 1,2,4;
