SELECT R.ROLNAME AS USERNAME,
	D.DATNAME AS "DB",
	CALLS ,
	ROUND(TOTAL_TIME::numeric,2) AS TOTAL_TIME,
	ROUND(MIN_TIME::numeric,4) AS MIN_TIME,
	ROUND(MAX_TIME::numeric,2) AS MAX_TIME,
	ROUND(TOTAL_TIME::numeric / CALLS,2) AS AVG_TIME,
	ROUND((100 * TOTAL_TIME / SUM(TOTAL_TIME::numeric) OVER ())::numeric, 2) AS PERCENTAGE_CPU,
	SUBSTRING(QUERY,1,100) AS SHORT_QUERY
	--QUERY as FULL_QUERY --> To view full query
FROM PG_STAT_STATEMENTS SS
JOIN PG_ROLES R ON SS.USERID = R.OID
JOIN PG_DATABASE D ON SS.DBID = D.OID
WHERE D.DATNAME not in ('rdsadmin') 
AND QUERY NOT IN ('COMMIT','ROLLBACK')
AND QUERY NOT LIKE '/*pga4dash*/%'  -- Removing pgAdmin dashboard querys
ORDER BY AVG_TIME DESC
 -- order by calls desc
LIMIT 20;
